class Parameter:
    epoch: int
    learning_rate: float
    batch_size_test: int
    batch_size_train: int
    data_path: str
    name: str
    step: int
    train_report_rate: float
    device: str
